# Generated by Django 4.2.5 on 2024-02-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionaire",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
