# Generated by Django 4.2.5 on 2024-02-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0002_questionaire_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionaire",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionaire",
            name="pub_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date published"
            ),
        ),
        migrations.AlterField(
            model_name="questionaire",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
